name: medicare
description: "Medical project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  flutter_animate: ^4.5.0
  toastification: ^1.2.1
  dio: ^5.4.1
  url_launcher: ^6.2.5
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  local_auth: ^2.2.0
  lottie: ^3.1.0
  animated_loading_border: ^0.0.2
  flutter_sound: ^9.4.6
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  image_cropper: ^1.5.1
  date_format: ^2.0.7
  voice_message_package: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
